/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: vertigocrayon (https://sketchfab.com/vertigocrayon)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/peaceful-mountain-village-d2d34e3fb0ef46f088b4b12a994a3a87
title: Peaceful mountain village
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/mountain.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.03}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, -0.04, 0]}>
            <group rotation={[-Math.PI / 2, 0, 0]}>
              <mesh geometry={nodes.SM_Mounain_Cloud_0.geometry} material={materials.Cloud} />
            </group>
          </group>
          <group position={[0, -0.04, 0]}>
            <group rotation={[-Math.PI / 2, 0, 0]}>
              <mesh geometry={nodes.SM_Clouds_2_0.geometry} material={materials.material} />
            </group>
          </group>
          <group position={[0, -0.04, 0]}>
            <group rotation={[-Math.PI / 2, 0, 0]}>
              <mesh geometry={nodes.SM_Houses_1_0.geometry} material={materials.material_2} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/mountain.gltf')
